import type { Metadata } from "next";
import { supabase } from "../../lib/supabase";
import CasinoDirectory from "./CasinoDirectory";
import { SITE_URL } from "../../lib/seo";

export type CategoryKey="betting-sites"|"online-casinos"|"sportsbooks"|"casino-bonuses"|"betting-bonuses"|"bangladesh-betting-sites";
export const categoryConfig:Record<CategoryKey,{title:string;description:string;keywords:string[];filter:(c:any)=>boolean}>={
 "betting-sites":{title:"Betting Sites — Compare Platforms",description:"Browse betting site profiles, offers, payment methods and availability on BetBass.",keywords:["betting sites","betting site comparison"],filter:c=>c.operator_type==="sportsbook"||c.operator_type==="both"},
 "online-casinos":{title:"Online Casinos — Compare Casino Platforms",description:"Browse online casino profiles, offers, payment methods and availability on BetBass.",keywords:["online casinos","casino comparison"],filter:c=>c.operator_type==="casino"||c.operator_type==="both"},
 "sportsbooks":{title:"Sportsbooks — Compare Betting Platforms",description:"Browse sportsbook profiles, offers, payment methods and availability on BetBass.",keywords:["sportsbooks","sports betting"],filter:c=>c.operator_type==="sportsbook"||c.operator_type==="both"},
 "casino-bonuses":{title:"Casino Bonuses — Compare Offers",description:"Explore casino platform offers and bonus information listed on BetBass.",keywords:["casino bonuses","casino offers"],filter:c=>c.operator_type==="casino"||c.operator_type==="both"},
 "betting-bonuses":{title:"Betting Bonuses — Compare Offers",description:"Explore betting and sportsbook offers listed on BetBass.",keywords:["betting bonuses","sportsbook bonuses"],filter:c=>c.operator_type==="sportsbook"||c.operator_type==="both"},
 "bangladesh-betting-sites":{title:"Bangladesh Betting Sites — Platform Directory",description:"Browse betting and casino platforms listed for Bangladesh GEO research. Always verify current eligibility and local requirements.",keywords:["Bangladesh betting sites","Bangladesh sportsbook","Bangladesh casino"],filter:c=>Boolean(c.bangladesh_priority)||c.countries?.some((x:string)=>x.toLowerCase().includes("bangladesh"))}
};
export function categoryMetadata(category:CategoryKey):Metadata{const c=categoryConfig[category];return{title:c.title,description:c.description,keywords:c.keywords,alternates:{canonical:`/${category}`},robots:{index:true,follow:true},openGraph:{title:`BetBass — ${c.title}`,description:c.description,url:`/${category}`,type:"website"}}}
export async function renderCategory(category:CategoryKey){
 const c=categoryConfig[category];
 const {data}=await supabase.from("betbass_casinos").select("*").eq("active",true).order("priority",{ascending:true}).order("bangladesh_priority",{ascending:false}).order("featured",{ascending:false}).order("name");
 const casinos=(data??[]).filter(c.filter);
 const siteUrl=SITE_URL;
 const itemList=casinos.slice(0,100).map((casino,index)=>({"@type":"ListItem",position:index+1,name:casino.name,url:`${siteUrl}/casinos/${casino.slug}`}));
 const jsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:c.title,description:c.description,url:`${siteUrl}/${category}`,isPartOf:{"@type":"WebSite",name:"BetBass",url:siteUrl},mainEntity:{"@type":"ItemList",name:c.title,numberOfItems:itemList.length,itemList}}; const breadcrumbJsonLd={"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"BetBass","item":siteUrl},{"@type":"ListItem","position":2,"name":c.title,"item":`${siteUrl}/${category}`}]};
 return <main className="min-h-screen px-6 py-10"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbJsonLd)}}/><div className="mx-auto max-w-7xl"><a href="/" className="text-sm text-white/45 hover:text-white">← Back to BetBass</a><header className="mt-8 max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">BETBASS DIRECTORY</p><h1 className="mt-2 text-4xl font-black md:text-6xl">{c.title}</h1><p className="mt-5 text-lg leading-8 text-white/55">{c.description}</p><p className="mt-4 text-sm leading-6 text-white/45">Browse the listed platforms below and open individual profiles for operator type, published offer information, payment methods, GEO notes and other available details. Terms, eligibility and availability can change, so verify current conditions with the operator.</p></header><nav aria-label="Related BetBass categories" className="mt-8 flex flex-wrap gap-2">{(Object.keys(categoryConfig) as CategoryKey[]).filter((key)=>key!==category).map((key)=><a key={key} href={`/${key}`} className="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-white/60 hover:text-white">{categoryConfig[key].title}</a>)}</nav><section className="mt-10"><CasinoDirectory casinos={casinos}/></section><section className="mt-10 rounded-3xl border border-white/10 bg-white/5 p-7"><h2 className="text-2xl font-black">About this BetBass category</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-white/50">This directory is an informational comparison page. Platform details are based on information currently supplied to BetBass and may change over time. Use each platform profile and the operator's current terms to verify offers, payment methods, licensing and country availability before making decisions.</p></section></div></main>;
}